### ISSUE TITLE
panic - any ideas?

### ISSUE THREAD

**Issue by Shizzlebix** [exzz/netatmo-api-go#6]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47da03]

goroutine 1 [running]:
panic(0x6345a0, 0xc42000c100)
        /usr/lib/go-1.7/src/runtime/panic.go:500 +0x1a1
github.com/exzz/netatmo-api-go.(*Device).Data(0xc4202f2700, 0xc420076db0, 0xc4200e9328)
        /root/netatmo-api-go/src/github.com/exzz/netatmo-api-go/weather.go:278 +0x953
main.main()

**Comment by guckykv** [comment]
I think I've had the same problem yesterday. Everything works fine for month and then this SIGSEGV.

The reason was, that one of my sensors run out of battery. Then the Netatmo API seems to deliver a data structure which misses important fields (like last updated) which leads to this error.

After replacing the batteries everything again works fine.
